### ISSUE TITLE
How to add a new diagram?

### ISSUE THREAD

**Issue by jhannes** [plantuml/word-template#1]
I'm enjoying using this Word template for writing technical documents.

One thing puzzles me: When I add a new diagram, I've found no better way that copying and pasting the "green text" for an existing diagram and modifying the contents. Is there a better way?

**Comment by compie** [comment]
You don't have to use copy/paste, you can also type:
@startuml
@enduml

But a new 'Insert PlantUML image' button would improve the usability.

**Comment by jhannes** [comment]
Thank you for the response - I got it to work.

As a very simple improvement, it would be good to put this in the documentation. :-)
