### ISSUE TITLE
Compiling/Generating and preference buttons no longer work

### ISSUE THREAD

**Issue by tony-p** [plantuml/word-template#19]
![image](https://github.com/plantuml/word-template/assets/11678396/430ecd64-5953-4f94-98b2-63d1001b7eae)

I have been using the plugin for awhile, and have suddenly started getting the above error when ever trying to regenerate a diagram or clicking the preferences button.

Toggling auto-format and whether source is visible all still works.

I have the latest version of the template document (PlantUML_Template_v34 word 2016) and have jar file version 1.2023.10. Get the same behaviour with 1.2023.12.

It may be that word has updated since I last used the plugin.

Word version -> Microsoft® Word for Microsoft 365 MSO (Version 2310 Build 16.0.16924.20054) 64-bit

**Comment by rubeecube** [comment]
Try new version https://github.com/plantuml/word-template/blob/master/Template_Word_2016/PlantUML_Template_v35.dotm

**Comment by tony-p** [comment]
Great that fixed it! thanks
