### ISSUE TITLE
How to get non-English characters to work?

### ISSUE THREAD

**Issue by jhannes** [plantuml/word-template#2]
I think Plantuml by default uses ISO-8859-1 while Word uses unicode. This means that non-english characters (in my case, Norwegian characters like "æ", "ø" and "å" ) in diagrams gets printed as weird and incorrect pairs of letters.

Is it possible to for example do a character conversion as a Preference?

Here is an example:

@startuml
Johannes -> compie: Is there any way to get non-english characters like "æ", "ø" and "å" (Norwegian characters to work?
@enduml

**Comment by arnaudroques** [comment]
Could you try with this beta version ?
https://www.dropbox.com/s/koo42q3d9gxw288/plantuml.jar?dl=0
This version forces UTF-8 encoding when Word (that is -word flag) is used, whatever is the default system charset.
(BTW you can know your default charset using `java -jar plantuml.jar -help `see http://plantuml.com/faq )
If we are lucky, it may simply work.
Tell us about the result!
Thanks

**Comment by jhannes** [comment]
It worked with the beta version. I got some strange behavior at first, though.

Thanks!
