### ISSUE TITLE
VBA Issue: GetLocalFilePath for one drive

### ISSUE THREAD

**Issue by rubenvy** [plantuml/word-template#20]
See: https://gist.github.com/guwidoe/038398b6be1b16c458365716a921814d

'@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
'                              IMPORTANT NOTE!
'If you are using this solution and you downloaded it before the 2nd of October
'2023, please update your code to the current version, as otherwise the function
'might stop working for OneDrive version 23.184.0903.0001 and newer.
'@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

**Comment by rubeecube** [comment]
Wrote a code to fix this issue Work locally (Except for new document not saved)
